#!/bin/bash

source /projects/stars/app/evry/conf/env.sh
APP_HOME=/projects/stars/var/pubmed
APP_HOME=/projects/stars/app/episteme

$SPARK_HOME/bin/spark-submit   \
  --num-executors        50    \
  --total-executor-cores 100   \
  --executor-memory      20G   \
  --py-files $APP_HOME/mesh.py \
  $APP_HOME/chemotext.py $*

exit 0
